---
- name: base configuration # Should be run first after installing the OS
  hosts: private

  roles:
    - role: bootstrap
      become: true

  tasks:
    - name: upgrade system
      apt:
        update_cache: true
        upgrade: true
      become: true

    - name: install aptitude and upgrade system
      apt:
        name: aptitude
        state: present
        update_cache: true
      become: true

    - name: install basic software packages
      apt:
        name: "{{ apt_base_packages }}"
        state: present
        update_cache: yes
        autoclean: true
        autoremove: true
      become: true

    - name: update locate-db
      command: updatedb -v

#    # https://askubuntu.com/questions/1032476/ubuntu-18-04-no-dns-resolution-when-connected-to-openvpn
#    # - name: fix DNS resolution when connected to OpenVPN
#    # install https://github.com/jonathanio/update-systemd-resolved
#    # enable stub resolver https://github.com/jonathanio/update-systemd-resolved#stub-resolver
#
#    # This is a manual step
#    # OpenVPN configuration: https://github.com/jonathanio/update-systemd-resolved#openvpn-configuration
#    # Added as first line
